/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as MicaRouteImport } from './routes/mica'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as IaRouteImport } from './routes/ia'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const MicaRoute = MicaRouteImport.update({
  id: '/mica',
  path: '/mica',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dados': typeof DadosRoute
  '/ia': typeof IaRoute
  '/mapa': typeof MapaRoute
  '/mica': typeof MicaRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dados': typeof DadosRoute
  '/ia': typeof IaRoute
  '/mapa': typeof MapaRoute
  '/mica': typeof MicaRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dados': typeof DadosRoute
  '/ia': typeof IaRoute
  '/mapa': typeof MapaRoute
  '/mica': typeof MicaRoute
  '/relatorio': typeof RelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dados'
    | '/ia'
    | '/mapa'
    | '/mica'
    | '/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/dados' | '/ia' | '/mapa' | '/mica' | '/relatorio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dados'
    | '/ia'
    | '/mapa'
    | '/mica'
    | '/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DadosRoute: typeof DadosRoute
  IaRoute: typeof IaRoute
  MapaRoute: typeof MapaRoute
  MicaRoute: typeof MicaRoute
  RelatorioRoute: typeof RelatorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mica': {
      id: '/mica'
      path: '/mica'
      fullPath: '/mica'
      preLoaderRoute: typeof MicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DadosRoute: DadosRoute,
  IaRoute: IaRoute,
  MapaRoute: MapaRoute,
  MicaRoute: MicaRoute,
  RelatorioRoute: RelatorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
